### ISSUE TITLE
can´t compile the code 

### ISSUE THREAD

**Issue by MrG1981** [stooged/PS4-Server#2]
Arduino: 1.8.5 (Windows 10), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, 4M (3M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 921600"

...\PS4-Server-master\PS4_Server\PS4_Server.ino: In function 'void setup()':

PS4_Server:628: error: no matching function for call to 'ESP8266WebServer::begin(int&)'

   webServer.begin(WEB_PORT);

                           ^

...\PS4-Server-master\PS4_Server\PS4_Server.ino:628:27: note: candidate is:

In file included from ...\PS4-Server-master\PS4_Server\PS4_Server.ino:2:0:

...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\libraries\ESP8266WebServer\src/ESP8266WebServer.h:76:8: note: void ESP8266WebServer::begin()

   void begin();

        ^

C:\Users\MrG\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\libraries\ESP8266WebServer\src/ESP8266WebServer.h:76:8: note:   candidate expects 0 arguments, 1 provided

exit status 1
no matching function for call to 'ESP8266WebServer::begin(int&)'

**Comment by stooged** [comment]
You have to add the latest esp8266 board/platform to your Arduino its at version 2.4.1 you have 2.4.0

https://github.com/esp8266/Arduino/blob/master/doc/installing.rst
